blank_issues_enabled: false
contact_links:
  - name: Home Assistant community support
    url: https://community.home-assistant.io/
    about: Ask general Home Assistant usage questions in the community forum.
